attribute = "red"
keyword = "dark_white"
"keyword.directive" = "red" # -- preprocessor comments (#if in C)
namespace = "red"
punctuation = "magenta"
"punctuation.delimiter" = "magenta"
operator = "red"
special = "dark_magenta"
"variable.other.member" = "white"
variable = "magenta"
# variable = "dark_white" # TODO: metavariables only
# "variable.parameter" = { fg = "magenta", modifiers = ["underlined"] }
"variable.parameter" = { fg = "magenta" }
"variable.builtin" = "dark_green"
type = "white"
"type.builtin" = "white" # TODO: distinguish?
constructor = "red"
function = "white"
"function.macro" = "red"
"function.builtin" = "white"
tag = "dark_white"
comment = "dark_cyan"
constant = "white"
"constant.builtin" = "white"
string = "green"
"constant.numeric" = "bright_blue"
"constant.character.escape" = "dark_magenta"
# used for lifetimes
label = "dark_magenta"

"markup.heading" = "red"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "green", modifiers = ["underlined"] }
"markup.link.text" = "dark_white"
"markup.raw" = "dark_white"

"diff.plus" = "#a3be8c"
"diff.minus" = "#fb7d89"
"diff.dark_blue" = "#6c99a6"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "black" }
"ui.background.separator" = { fg = "blue" }
"ui.linenr" = { fg = "blue" }
"ui.linenr.selected" = { fg = "red" }
"ui.statusline" = { fg = "red", bg = "bright_black" }
"ui.statusline.inactive" = { fg = "magenta", bg = "bright_black" }
"ui.popup" = { bg = "bright_black" }
"ui.window" = { fg = "dark_black" }
"ui.help" = { bg = "dark_magenta", fg = "black" }

"ui.text" = { fg = "magenta" }
"ui.text.focus" = { fg = "white" }
"ui.text.inactive" = "dark_cyan"
"ui.virtual" = { fg = "blue" }

"ui.virtual.indent-guide" = { fg = "blue" }

"ui.selection" = { bg = "black" }
"ui.selection.primary" = { bg = "dark_magenta" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "dark_blue" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "#black", bg = "bright_black" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "dark_black" }
"ui.highlight" = { bg = "dark_black" }

"ui.menu" = { fg = "magenta", bg = "bright_black" }
"ui.menu.selected" = { fg = "bright_black", bg = "white" }
"ui.menu.scroll" = { fg = "magenta", bg = "blue" }

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "dark_blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "dark_red", style = "curl" } }

"ui.virtual.ruler" = { bg = "bright_black" }

warning = "yellow"
error = "dark_red"
info = "dark_blue"
hint = "green"

[palette]
# New
black =   "#1d1f21"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#88c0d0"
magenta = "#b48ead"
#cyan =    "#8fbcbb"
white =   "#d8dee9"
orange = "#d08770"
# 
#bright_black =   "#4c566a"
bright_black =   "#344043"
#bright_red =     "#fb7d89"
#bright_green =   "#a3be8c"
#bright_yellow =  "#ffdc96"
bright_blue =    "#88c0d0"
#bright_magenta = "#b48ead"
#bright_cyan =    "#c2fdfb"
#bright_white =   "#fbf1c7"
# 
dark_black =   "#111111"
dark_red =     "#a3525a"
dark_green =   "#81966f"
#dark_yellow =  "#cfb278"
dark_blue =    "#6c99a6"
dark_magenta = "#90708a"
dark_cyan =    "#77a0a0"
dark_white =   "#fbf1c7"
