# Pugnace's personal configuration
# https://docs.helix-editor.com/configuration.html
theme = "pugnaceTheme"

[editor]
scrolloff = 5
mouse = false
middle-click-paste = true
scroll-lines = 3
shell =["sh", "-c"]
line-number = "relative"
cursorline = true
cursorcolumn = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"] # Need to understand what it is
auto-completion = true
auto-format = true
auto-save = false
idle-timeout = 400
completion-trigger-len = 2
auto-info = true
true-color = false
rulers = [90]
bufferline = "always"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "separator", "total-line-numbers", "file-encoding"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
#max-depth = None

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
#render = "all" # this one is so cool

[editor.whitespace.render]
space = "none"
tab = "all"
tabpad = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" 

[editor.indent-guides]
render = true
character = "┆" # "┆", "┊", "⸽"
skip-levels = 0

[keys.normal]
C-s = ":w"
C-o = ":q!"
"A-ret" = "insert_mode"
